---
# https://github.com/gluster/gluster-kubernetes/releases
gluster_kubernetes_version: "master"

# Use same version as used in docker image used in:
# https://github.com/gluster/gluster-kubernetes/blob/{{ gluster_kubernetes_version }}/deploy/kube-templates/glusterfs-daemonset.yaml#L23
# https://hub.docker.com/r/gluster/gluster-centos/dockerfile
glusterfs_version: "4.1"
