---
#ansible-playbook playbooks/1_node_setup/2_remote_nodes_setup.yml -i inventories/sandbox_nodes.ini
#ansible-playbook playbooks/1_node_setup/2_remote_nodes_setup.yml --ask-become-pass -i inventories/example_nodes.ini

# If your ssh public key is not yet added to remote nodes, use "--ask-pass" to
# specify the password
#ansible-playbook playbooks/1_node_setup/2_remote_nodes_setup.yml --ask-pass --ask-become-pass -i inventories/example_nodes.ini

- import_playbook: remote_connection.yml
- import_playbook: node_setup.yml
