---
#ansible-playbook playbooks/1_node_setup/keepalived.yml -i inventories/sandbox_nodes.ini
#ansible-playbook playbooks/1_node_setup/keepalived.yml --ask-become-pass -i inventories/example_nodes.ini

- name: Setup_keepalived
  tags: Setup_keepalived
  hosts: keepalived_nodes
  vars_files: custom/keepalived/{{ inventory }}_variables.yml
  tasks:
  - import_role:
      name: ../../roles/node_setup/keepalived
