apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: djangos.aya.pyxo.net
spec:
  group: aya.pyxo.net
  names:
    kind: Django
    listKind: DjangoList
    plural: djangos
    singular: django
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
