apiVersion: v1
kind: ServiceAccount
metadata:
  name: ayaapp-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ayaapp-operator
rules:
- apiGroups:
  - "*"
  resources:
  - '*'
  verbs:
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ayaapp-operator
subjects:
- kind: ServiceAccount
  name: ayaapp-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: ayaapp-operator
  apiGroup: rbac.authorization.k8s.io
