---
- when: "'keepalived_nodes' in group_names"
  become: true
  block:
  - name: Install_keepalived | {{ role_name | basename }}
    tags: Install_keepalived
    apt:
      name: "keepalived"
      update_cache: true
      state: present

  - name: Generate_keepalived_password | {{ role_name | basename }}
    tags: Generate_keepalived_password
    shell: openssl rand -hex $((20 + RANDOM % 10))
    register: keepalived_password

  - name: Create_keepalived_config | {{ role_name | basename }}
    tags: Create_keepalived_config
    blockinfile:
      path: "/etc/keepalived/keepalived.conf"
      block: "{{ lookup('template', 'templates/keepalived.conf.j2') }}"
      create: true
      marker: "# {mark} keepalived CONFIG MANAGED BY ANSIBLE ROLE {{ role_name | basename }}"

  - name: Restart_keepalived_and_enable_on_boot | {{ role_name | basename }}
    tags: Restart_keepalived_and_enable_on_boot
    systemd:
      name: keepalived
      enabled: true
      state: restarted
      daemon_reload: true
