---
# https://microk8s.io/docs/
- when:
    - "'microk8s_nodes' in group_names"
  block:
  - name: Install_microk8s | {{ role_name | basename }}
    tags: Install_microk8s
    become: true
    snap:
      name: microk8s
      channel: "{{ microk8s_channel }}"
      classic: true

  - name: Wait_for_microk8s_to_be_ready | {{ role_name | basename }}
    tags: Wait_for_microk8s_to_be_ready
    command: microk8s.status --wait-ready

  - name: Enable_microk8s_addons | {{ role_name | basename }}
    tags: Enable_microk8s_addons
    become: true
    loop: ['rbac', 'dns', 'storage', 'dashboard']
    shell: "microk8s.status --wait-ready | grep '{{ item }}: enabled' || microk8s.enable {{ item }}"

  - name: Add_kubectl_alias | {{ role_name | basename }}
    tags: Add_kubectl_alias
    become: true
    command: snap alias microk8s.kubectl kubectl

  - name: Create_microk8s_kubeconfig | {{ role_name | basename }}
    tags: Create_microk8s_kubeconfig
    shell: microk8s.kubectl config view --raw > {{ ansible_user_dir }}/.kube/config

  - name: Add_current_user_to_microk8s_group | {{ role_name | basename }}
    tags: Add_current_user_to_microk8s_group
    become: true
    user:
      name: "{{ ansible_user_id }}"
      groups: microk8s
      append: true
