---
- name: Check_if_project_is_already_installed
  tags: Check_if_project_is_already_installed
  shell: kubectl exec $(kubectl get pods -l app=aya-python --no-headers -o custom-columns=":metadata.name" | tail -n 1) -c uwsgi -- bash -c "test -f {{ apps_dir }}/{{ deployment_env }}/{{ project }}/manage.py"
  ignore_errors: true
  register: project_is_installed_check
  changed_when: false

- when: project_is_installed_check.rc == 1
  block:
  - name: Create_project_setup_daemonset | {{ role_name | basename }}
    tags: Create_project_setup_daemonset
    k8s:
      definition: "{{ lookup('template', 'templates/project_setup_daemonset.yaml.j2') }}"

  - name: Wait_for_project_setup_daemonset_to_be_ready | {{ role_name | basename }}
    tags: Wait_for_project_setup_daemonset_to_be_ready
    shell: sleep 5 && kubectl rollout status daemonset/aya-project-setup-python-{{ project_python_version | regex_replace('\.', '-') }}
    changed_when: false

  - name: Get_project_setup_pods | {{ role_name | basename }}
    tags: Get_project_setup_pods
    shell: kubectl get pods -l app=aya-project-setup-python-{{ project_python_version | regex_replace('\.', '-') }} --no-headers -o custom-columns=":metadata.name"
    register: project_setup_pods
    changed_when: false

  - name: Add_project_setup_pods_to_ansible_inventory | {{ role_name | basename }}
    tags: Add_project_setup_pods_to_ansible_inventory
    add_host:
      name: "{{ item }}"
      groups: aya_project_setup_pods
      ansible_connection: kubectl
    changed_when: false
    loop: "{{ project_setup_pods.stdout_lines }}"
